### ISSUE TITLE
Github 登陆失败

### ISSUE THREAD

**Issue by Yanhua67** [xjh22222228/tomato-work#16]
首次使用github登陆时会进入404 
本地的server是开着的
大佬还在吗
![1](https://user-images.githubusercontent.com/27847443/120279363-eb406800-c2e8-11eb-8d59-377a715bcc36.PNG)

**Comment by qtzxly** [comment]
我也是这样

**Comment by inspire-lts** [comment]
@xjh22222228  作者您好，我本地启动的时候不能显示验证码，所以我就用github登录。但是github登录，报错为`Error: connect ECONNREFUSED 127.0.0.1:7003`。请问作者能解决一下吗，俺想研究下您代码学习学习。

**Comment by xjh22222228** [comment]
@inspire-lts  本地需要服务也要启动，或者 `npm run start:prod`  直接连线上。

**Comment by inspire-lts** [comment]
@inspire-lts 谢谢已经解决。建议大佬在reademe写一下，才看见其他关闭的issue里也有人提到。
