### ISSUE TITLE
点击日志管理会报错

### ISSUE THREAD

**Issue by Linon419** [xjh22222228/tomato-work#22]
就像这样
![image](https://user-images.githubusercontent.com/29937602/180208359-fe98b1cc-1640-4100-8e2a-b91e6aee06dd.png)
而且为啥启动项目报错
21:54:16 [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:7003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by xjh22222228** [comment]
连的本地的，你得把本地服务也起来， 否则这样 `npm run start:prod`  连线上服务
