### ISSUE TITLE
想登陆看看，结果你要我私有仓库的授权？

### ISSUE THREAD

**Issue by IrvingOS** [xjh22222228/tomato-work#24]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49826892/196601224-acbd480d-4e3b-4576-9f79-f6add25cb6f0.png">
现在的开源都这么玩的？

**Comment by xjh22222228** [comment]
你没看 README 有测试账号可以登录？？？？？？？？？？？

第二：要你登录了？

第三：这是开源项目，挨着你了。 CNM。

**Comment by xjh22222228** [comment]
出门左转， 真庆幸你打开了这个项目，GUN。

还有给你科普一下，这是默认授权，不回去好好喂猪，来写什么代码？
