### ISSUE TITLE
redux

### ISSUE THREAD

**Issue by wocswang** [xjh22222228/tomato-work#6]
大佬，我最近也是在用react+ts写PC项目，但是在状态这块一直拿不定用哪个好，redux ,dva mobx ,umi等所以想请教一下，哪个好用方便，react-redux用的我很难受

**Comment by xjh22222228** [comment]
本项目用的是 Redux,  嫌麻烦可以直接上 `Umi` 配套 `Dva`

**Comment by wocswang** [comment]
你好，我想问下就是配置别名这块在哪个文件配置的，没找到

**Comment by xjh22222228** [comment]
https://github.com/xjh22222228/tomato-work/blob/master/config/webpack.config.js#L292

**Comment by wocswang** [comment]
想咨询一下，状态管理这块，现在这块太混乱了，有没有什么好的推荐的，项目呢是不用umi感觉太重了

**Comment by xjh22222228** [comment]
@wocswang  可以用 useReducer
