### ISSUE TITLE
项目启动

### ISSUE THREAD

**Issue by wocswang** [xjh22222228/tomato-work#7]
你好，我把前端项目clone下来后，启动后，页面一直是加载状态，没有显示页面，调试器中也没有任何报错

**Comment by xjh22222228** [comment]
用的什么浏览器，换个浏览器试试？

**Comment by wocswang** [comment]
用的chrome

**Comment by xjh22222228** [comment]
你是用的 yarn 吗，这边都是可以的。

**Comment by wocswang** [comment]
我用的npm install

**Comment by wocswang** [comment]
那我把包都删掉然后yarn试试

**Comment by wocswang** [comment]
是这样的，我现在在学习ts+react,所以那你这个项目练练手，然后就是我现在就是写了两个页面就是Login 和Home这俩个，然后启动后就是一直在加载中，也没有报错，所以我clone下来后试试

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100038724-298f3300-2e3f-11eb-9a1e-01afc5884972.png)
装完包后启动就是这样了

**Comment by xjh22222228** [comment]
建议不要使用 CMD，用 GIT BASH 试试， Node.js 版本 >=12

**Comment by wocswang** [comment]
页面出来了，就是加载的特别慢，不知道是不是我电脑的原因
