### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wocswang** [xjh22222228/tomato-work#8]
你好，我现在从新走一遍项目，就是我现在写了login组件和main-entry homeIndex组件，然后我登录跳转时，始终跳转不到主页去，还是停留在登录页
![image](https://user-images.githubusercontent.com/23565529/100317083-b29c9a80-2ff6-11eb-99c0-06624f9b51ab.png)一直跳转不到主页

**Comment by xjh22222228** [comment]
没权限所有跳转不了，是账号密码登录吗？

**Comment by wocswang** [comment]
对，用的test 123456登录的

**Comment by wocswang** [comment]
因为github那个登录报500,所以就没有用这个，server端已经部署好了

**Comment by wocswang** [comment]
我看local接口请求数据已经成功了

**Comment by wocswang** [comment]
就是history.replace这没有跳转

**Comment by wocswang** [comment]
这个需要我怎么处理下才可以跳转

**Comment by xjh22222228** [comment]
你部署服务器，那客户端是连的本地接口？

**Comment by wocswang** [comment]
对，我本地启动的server的项目的npm run dev然后客户端链接的本地

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100318405-f0022780-2ff8-11eb-908d-cd26e49dcc0d.png)

**Comment by xjh22222228** [comment]
那就是数据库没有这个账号，你直接用GITHUB 授权登录，应该是没问题的。

**Comment by wocswang** [comment]
对，我刚才看了数据库还没有数据了，github这块我没有动，用的还是你的配置，需要我单独配置吗

**Comment by xjh22222228** [comment]
第一次使用GITHUB授权登录后之后就可以使用账号密码登录了。

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100318820-9e0dd180-2ff9-11eb-96bf-97f62102d3e1.png)
我现在使用github登录就是报这个错误

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100318935-d3b2ba80-2ff9-11eb-9033-325ef3d2aaa8.png)
这些我都没有动过

**Comment by xjh22222228** [comment]
```
151.101.72.249 github.global.ssl.fastly.net
13.250.177.223 github.com
```
将上面的加到  C:\Windows\System32\drivers\etc\hosts 上去。

**Comment by wocswang** [comment]
我去试试

**Comment by wocswang** [comment]
我添加了但是还是不行，还是那个错误，需要重启项目吗

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100320712-8d128f80-2ffc-11eb-9d55-3ef669b9e847.png)

**Comment by xjh22222228** [comment]
你是不是没改代理地址？ .env 文件

**Comment by wocswang** [comment]
![Uploading image.png…]()

**Comment by wocswang** [comment]
一开始没有改，我改成这样后
![image](https://user-images.githubusercontent.com/23565529/100321616-ec24d400-2ffd-11eb-9185-c373c1abec7a.png)

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100321646-f8109600-2ffd-11eb-85a7-0d229fac2c90.png)

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100322259-f85d6100-2ffe-11eb-9c65-f0a032afb874.png)
感觉还是被墙了

**Comment by xjh22222228** [comment]
APP_PROXY=http://localhost:7003

**Comment by wocswang** [comment]
下面的端口好是客户端的端口号对吧

**Comment by xjh22222228** [comment]
下面是启动端口。

**Comment by wocswang** [comment]
![image](https://user-images.githubusercontent.com/23565529/100323276-71a98380-3000-11eb-9dab-ccf3778b570f.png)
![image](https://user-images.githubusercontent.com/23565529/100323333-87b74400-3000-11eb-9856-4564e30f5dc0.png)

**Comment by wocswang** [comment]
我发现我本地不开vpn根本访问不了github

**Comment by xjh22222228** [comment]
嗯，那就是被墙了。现在好了吗

**Comment by wocswang** [comment]
开了以后可以访问，但是使用github授权就报这个

**Comment by wocswang** [comment]
稍等，我把代码拉下来试试
