### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wocswang** [xjh22222228/tomato-work#9]
我重新拉下代码后修改过.env后，然后就启动项目
![image](https://user-images.githubusercontent.com/23565529/100431531-43e13f00-30d3-11eb-9ffa-8532c8e6930a.png)我访问，结果就会自动跳转到index页面

**Comment by xjh22222228** [comment]
不修改代码，拉下来启动是否正常？

**Comment by wocswang** [comment]
我刚才把代码改回去了，然后还是这样

**Comment by xjh22222228** [comment]
你是否是使用 yarn 安装 ？

**Comment by wocswang** [comment]
用的yarn装的

**Comment by xjh22222228** [comment]
我刚刚用了台win10, node 14 试了下没问题，你检查下是否是你的环境出了问题。
